name: 'Netlify Deploy'

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:

       - name: Checkout under $GITHUB_WORKSPACE
         uses: actions/checkout@main

       - name: Set up NodeJS
         uses: actions/setup-node@v1
         with:
          node-version: 16

       - name: Install all dependencies
         run: npm install

       - name: Deploy to Netlify
         uses: jsmrcaga/action-netlify-deploy@master
         with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
